find_package(PkgConfig REQUIRED)
find_package(fmt REQUIRED)
find_package(range-v3 REQUIRED)
find_package(Boost REQUIRED)
if (WITH_SYMENGINE)
    find_package(SymEngine REQUIRED)
    link_libraries(symengine)
endif()
if (WITH_GMPXX)
    pkg_check_modules(gmpxx REQUIRED IMPORTED_TARGET "gmpxx")
    link_libraries(PkgConfig::gmpxx)
endif()

link_libraries(fmt::fmt range-v3::range-v3 pthread Boost::boost)
